services:
  - type: pserv
    name: todos-db
    runtime: postgres
    plan: free
  
  - type: pserv
    name: todos-cache
    runtime: redis
    plan: free
  
  - type: web
    name: todo-api
    plan: free
    env: docker  # ✅ This is correct for Docker
    healthCheckPath: /health
    # Add this line:
    dockerfilePath: ./Dockerfile  # Point to your Dockerfile location
    envVars:
      - key: DB_SOURCE
        fromService:
          type: pserv
          name: todos-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: todos-cache
          property: connectionString