# render.yaml
services:
  # PostgreSQL Database
  - type: pserv
    name: todos-db
    env: postgres  # Use 'env', not 'runtime'
    plan: free
    
  # Redis Cache  
  - type: pserv
    name: todos-cache
    env: redis     # Use 'env', not 'runtime'
    plan: free
    
  # Go Web Service
  - type: web
    name: todo-api
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DB_SOURCE
        fromService:
          type: pserv
          name: todos-db
          property: connectionString  # This should work for pserv
      - key: REDIS_URL
        fromService:
          type: pserv
          name: todos-cache
          property: connectionString  # This should work for pserv