# In render.yaml

services:
  # This is our PostgreSQL Database service.
  - type: pserv
    name: todos-db
    runtime: postgres # FIX: We must specify the runtime
    plan: free

  # This is our Redis Cache service.
  - type: pserv
    name: todos-cache
    runtime: redis # FIX: We must specify the runtime
    plan: free

  # This is our Go Web Service (your API).
  - type: web
    name: todo-api
    plan: free
    env: docker
    healthCheckPath: /health
    envVars:
      - key: DB_SOURCE # This part is now correct
        fromService:
          type: pserv
          name: todos-db
          property: connectionString
      - key: REDIS_URL # FIX: We get the full URL from Render
        fromService:
          type: pserv
          name: todos-cache
          property: connectionString