# render.yaml - Using Render's Built-in Databases
services:
  # Render's Redis Cache
  - type: keyvalue
    name: todos-cache
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    
  # Go Web Service
  - type: web
    name: todo-api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      # Connect to Render's PostgreSQL
      - key: DB_SOURCE
        fromDatabase:
          name: todos-db
          property: connectionString
          
      # Redis Address (if your app uses this instead of REDIS_URL)
      - key: REDIS_ADDR
        fromService:
          type: keyvalue
          name: todos-cache
          property: connectionString
      
      # JWT Secret - this was missing and causing the crash!
      - key: JWT_SECRET
        generateValue: true
      
      # Port
      - key: PORT
        value: "8080"
      
      # Environment (optional - helps your app know it's in production)
      - key: ENV
        value: "production"

# Render's PostgreSQL Database
databases:
  - name: todos-db
    plan: free