# render.yaml
services:
  # Redis Cache - this stays in services
  - type: keyvalue  # Use 'keyvalue' instead of 'pserv' for Redis
    name: todos-cache
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    
  # Go Web Service
  - type: web
    name: todo-api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DB_SOURCE
        fromDatabase:  # Use 'fromDatabase' for PostgreSQL
          name: todos-db
          property: connectionString
      - key: REDIS_URL
        fromService:   # Use 'fromService' for Redis
          type: keyvalue
          name: todos-cache
          property: connectionString

# PostgreSQL databases go in a separate section
databases:
  - name: todos-db
    plan: free