# k8s/api.yaml

apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  # The value for JWT_SECRET is the base64 of "my_super_secret_key"
  JWT_SECRET: {{.Values.api.config.jwtSecret | b64enc | quote}}
  # The value for DB_SOURCE is the base64 of the internal K8s connection string
  DB_SOURCE: {{.Values.api.config.DB_SOURCE | b64enc | quote}}

---
apiVersion: v1
kind: Service
metadata:
  name: todo-api-service # Renamed for consistency
spec:
  # This makes the service accessible from outside the cluster (on your Mac)
  type: NodePort
  selector:
    app: todo-api # Finds the Pods to send traffic to
  ports:
    - protocol: TCP
      port: {{.Values.api.service.port}}       # The Service's internal port
      targetPort: {{.Values.api.service.port}} # The port on the Pods

---
apiVersion: apps/v1 # FIX: Changed from app/v1 to apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
spec:
  replicas: {{.Values.api.replicaCount}}
  selector:
    matchLabels:
      app: todo-api
  # FIX: Added the required 'template' section for the Pod blueprint
  template:
    metadata:
      # This label on the Pod MUST match the selector above
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api-container
          # IMPORTANT: Make sure this is your Docker Hub username and image name
          image: dadwalabhishek/todo-api-final:latest
          ports:
            - containerPort: {{.Values.api.service.port}} 
          env:
            - name: REDIS_ADDR
              value: "redis-service:6379"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: JWT_SECRET
            - name: DB_SOURCE
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DB_SOURCE